"""comment table and relationship one tomany with contributors

Revision ID: 0ba561d52698
Revises: 3da85173fec1
Create Date: 2018-09-16 22:07:54.220111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba561d52698'
down_revision = '3da85173fec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_contributor_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'contributor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('contributor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_contributor_id_fkey', 'comments', 'contributor', ['contributor_id'], ['id'])
    # ### end Alembic commands ###
