"""comment table and relationship one tomany with contributors

Revision ID: 3da85173fec1
Revises: 887ce05b9754
Create Date: 2018-09-16 22:03:44.074680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da85173fec1'
down_revision = '887ce05b9754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('contributor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'contributor', ['contributor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'contributor_id')
    # ### end Alembic commands ###
