"""comment table and relationship one tomany with contributors

Revision ID: 66ce124e0aea
Revises: 0ba561d52698
Create Date: 2018-09-16 22:32:45.884523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ce124e0aea'
down_revision = '0ba561d52698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('email', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint('comments_Follower_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'Follower_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('Follower_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_Follower_id_fkey', 'comments', 'Follower', ['Follower_id'], ['id'])
    op.drop_column('comments', 'name')
    op.drop_column('comments', 'email')
    # ### end Alembic commands ###
