"""changed blog pic settings to nullable true

Revision ID: 81887fe29010
Revises: 0b6735e0c1ba
Create Date: 2018-09-17 11:40:51.889952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81887fe29010'
down_revision = '0b6735e0c1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'blog_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'blog_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
