"""follower table

Revision ID: cdd8cee81fdd
Revises: 3aea4d816864
Create Date: 2018-09-14 12:13:11.399709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd8cee81fdd'
down_revision = '3aea4d816864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Follower', sa.Column('hash_pass', sa.String(length=60), nullable=True))
    op.drop_column('Follower', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Follower', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.drop_column('Follower', 'hash_pass')
    # ### end Alembic commands ###
